<script>
  import { createEventDispatcher } from "svelte";
  
  export let isListening = false;
  export let isThinking = false;
  export let currentTranscription = "Say 'Hey OMNI' or Press V";
  export let micMuted = false;
  export let outputMode = "auto";

  const dispatch = createEventDispatcher();

  let isVisible = false;
  let inputText = "";
  let showDedicatedWindow = false;
  let dedicatedAnswer = "";

  // Auto-hide logic
  $: if (isListening || isThinking || currentTranscription !== "Say 'Hey OMNI' or Press V") {
    isVisible = true;
  }

  function handleMicToggle() {
    dispatch("micToggle");
  }

  function handleExecute() {
    if (inputText.trim()) {
      dispatch("executeCommand", inputText);
      inputText = "";
    }
  }

  function handleKeyPress(event) {
    if (event.key === "Enter") {
      handleExecute();
    }
  }

  function handleFileDrop(event) {
    event.preventDefault();
    const files = event.dataTransfer.files;
    for (let file of files) {
      dispatch("executeCommand", `transcribe file ${file.name}`);
    }
  }

  function handleDragOver(event) {
    event.preventDefault();
  }

  // Simulate dedicated window with brief description as much needed
  $: if (currentTranscription && currentTranscription.length > 20 && !isListening && !isThinking) {
    showDedicatedWindow = true;
    dedicatedAnswer = currentTranscription;
    // Auto-hide dedicated window after 5 sec
    setTimeout(() => {
      showDedicatedWindow = false;
    }, 5000);
  }
</script>

<div class="bottom-widget-container" class:visible={isVisible}>
  <div 
    class="bottom-widget"
    on:drop={handleFileDrop}
    on:dragover={handleDragOver}
    role="region"
    aria-label="OMNI V2 Widget - Whisper Flow Style"
  >
    <div class="widget-header">
      <span class="widget-title">OMNI V2 - Whisper Flow Style</span>
      <div class="widget-buttons">
        <button class="mic-btn" class:muted={micMuted} on:click={handleMicToggle}>
          {micMuted ? "🔇" : "🎤"}
        </button>
        <button class="settings-btn" on:click={() => dispatch("openSettings")}>⚙️</button>
        <button class="close-btn" on:click={() => isVisible = false}>✕</button>
      </div>
    </div>

    <div class="widget-content">
      <div class="transcription-area" class:listening={isListening} class:thinking={isThinking}>
        {#if isListening}
          <span class="waveform">🎤 Listening... {currentTranscription}</span>
        {:else if isThinking}
          <span class="thinking">🧠 Thinking... {currentTranscription}</span>
        {:else}
          <span class="idle">{currentTranscription}</span>
        {/if}
      </div>

      <div class="input-area">
        <input 
          type="text" 
          bind:value={inputText} 
          on:keypress={handleKeyPress}
          placeholder="Type command or drag & drop audio/video to transcribe..."
          class="command-input"
        />
        <button on:click={handleExecute} class="send-btn">▶️</button>
      </div>

      <div class="widget-footer">
        <span>Mode: {outputMode} | Drag & drop files to transcribe | Auto-hide with buttons</span>
      </div>
    </div>
  </div>

  {#if showDedicatedWindow}
    <div class="dedicated-window">
      <div class="dedicated-header">
        <span>OMNI V2 Answer - Brief Description As Much Needed</span>
        <button on:click={() => showDedicatedWindow = false}>✕</button>
      </div>
      <div class="dedicated-content">
        {dedicatedAnswer}
        <div class="brief-desc">
          Brief description: This answer was generated by multi-agent chain with {dedicatedAnswer.split('|').length} steps, using 100+ tools routing, memory SQLite+Chroma, and is part of OMNI V2 JARVIS KILLER Phase 5 Fable 5 + GPT 5.6 Sol.
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .bottom-widget-container {
    position: fixed;
    bottom: -200px;
    left: 50%;
    transform: translateX(-50%);
    width: 600px;
    transition: bottom 0.3s ease;
    z-index: 9999;
  }

  .bottom-widget-container.visible {
    bottom: 20px;
  }

  .bottom-widget {
    background: rgba(10, 20, 40, 0.95);
    border: 1px solid rgba(0, 200, 255, 0.5);
    border-radius: 15px;
    padding: 15px;
    box-shadow: 0 0 30px rgba(0, 200, 255, 0.3);
    backdrop-filter: blur(10px);
  }

  .widget-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
  }

  .widget-title {
    font-size: 12px;
    color: cyan;
    font-weight: bold;
  }

  .widget-buttons {
    display: flex;
    gap: 5px;
  }

  .widget-buttons button {
    background: rgba(0, 200, 255, 0.2);
    border: 1px solid cyan;
    color: cyan;
    width: 30px;
    height: 30px;
    border-radius: 50%;
    cursor: pointer;
  }

  .mic-btn.muted {
    background: rgba(255, 0, 68, 0.5);
    border-color: red;
  }

  .transcription-area {
    min-height: 40px;
    padding: 10px;
    background: rgba(0, 0, 0, 0.5);
    border-radius: 8px;
    margin-bottom: 10px;
    color: white;
  }

  .transcription-area.listening {
    border: 1px solid rgba(50, 255, 100, 0.8);
    box-shadow: 0 0 10px rgba(50, 255, 100, 0.3);
  }

  .transcription-area.thinking {
    border: 1px solid rgba(255, 136, 0, 0.8);
    box-shadow: 0 0 10px rgba(255, 136, 0, 0.3);
  }

  .waveform {
    animation: pulse 0.5s infinite;
  }

  .input-area {
    display: flex;
    gap: 10px;
  }

  .command-input {
    flex: 1;
    background: rgba(0, 0, 0, 0.5);
    border: 1px solid rgba(0, 200, 255, 0.3);
    color: white;
    padding: 8px;
    border-radius: 5px;
  }

  .send-btn {
    background: rgba(0, 200, 255, 0.3);
    border: 1px solid cyan;
    color: cyan;
    padding: 8px 15px;
    border-radius: 5px;
    cursor: pointer;
  }

  .widget-footer {
    margin-top: 10px;
    font-size: 10px;
    color: rgba(0, 200, 255, 0.5);
    text-align: center;
  }

  .dedicated-window {
    position: fixed;
    bottom: 150px;
    left: 50%;
    transform: translateX(-50%);
    width: 500px;
    background: rgba(10, 30, 60, 0.98);
    border: 2px solid cyan;
    border-radius: 10px;
    padding: 15px;
    box-shadow: 0 0 40px rgba(0, 200, 255, 0.5);
    z-index: 10000;
  }

  .dedicated-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
    font-weight: bold;
    color: cyan;
  }

  .dedicated-content {
    color: white;
    font-size: 14px;
  }

  .brief-desc {
    margin-top: 10px;
    font-size: 11px;
    color: rgba(0, 200, 255, 0.7);
    font-style: italic;
  }

  @keyframes pulse {
    0% { opacity: 0.8; }
    50% { opacity: 1; }
    100% { opacity: 0.8; }
  }
</style>
