#!/usr/bin/env python3
"""Resolve every declared B01 profile and emit exact, hashed CPython 3.11 locks."""

from __future__ import annotations

import argparse
import json
import platform
import struct
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILES = ("core", "voice", "vision", "desktop", "dev", "all")


def _windows_product_type() -> int | None:
    if platform.system() != "Windows":
        return None
    get_version = getattr(sys, "getwindowsversion", None)
    if get_version is None:
        return None
    try:
        return int(get_version().product_type)
    except (AttributeError, TypeError, ValueError):
        return None


def _windows_build() -> int | None:
    if platform.system() != "Windows":
        return None
    get_version = getattr(sys, "getwindowsversion", None)
    if get_version is None:
        return None
    try:
        return int(get_version().build)
    except (AttributeError, TypeError, ValueError):
        return None


def _pointer_bits() -> int:
    return struct.calcsize("P") * 8


def _is_windows_x64() -> bool:
    return platform.machine().lower() in {"amd64", "x86_64"} and _pointer_bits() == 64


def _platform_slug() -> str:
    system = platform.system().lower()
    machine = platform.machine().lower()
    if machine in {"amd64", "x86_64"}:
        machine = "x86_64"
    return f"cpython-3.11-{system}-{machine}"


def _sha256(download_info: dict) -> str | None:
    archive = download_info.get("archive_info") or {}
    hashes = archive.get("hashes") or {}
    if hashes.get("sha256"):
        return str(hashes["sha256"])
    value = archive.get("hash")
    if isinstance(value, str) and value.startswith("sha256="):
        return value.split("=", 1)[1]
    return None


def _lock_text(profile: str, packages: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by scripts/resolve_profiles.py; do not edit.",
        f"# Profile: {profile}",
        f"# Interpreter: CPython {platform.python_version()}",
        f"# Platform: {platform.system()} {platform.machine()}",
        "# Install the OMNI wheel separately, then install this platform-specific lock with:",
        f"#   python -m pip install --no-deps --require-hashes -r {profile}.txt",
        "",
    ]
    for package in packages:
        if package["name"].lower() == "omni-agi":
            continue
        digest = package.get("sha256")
        if not digest:
            raise RuntimeError(f"resolved package has no SHA-256: {package}")
        lines.append(f"{package['name']}=={package['version']} --hash=sha256:{digest}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=(
            ROOT / "quality/evidence/B01/profile-resolution.json"
            if platform.system() == "Linux"
            else ROOT / "quality/evidence/B02" / f"{_platform_slug()}-profile-resolution.json"
        ),
    )
    parser.add_argument(
        "--lock-dir",
        type=Path,
        default=ROOT / "requirements/locks" / _platform_slug(),
    )
    parser.add_argument(
        "--profiles",
        nargs="+",
        choices=PROFILES,
        default=list(PROFILES),
        help="profile locks to resolve (default: every declared profile)",
    )
    args = parser.parse_args()

    if sys.version_info[:2] != (3, 11) or platform.python_implementation() != "CPython":
        parser.error("profile locks must be generated with CPython 3.11")
    if platform.system() == "Windows":
        windows_build = _windows_build()
        if not _is_windows_x64():
            parser.error(
                "Windows product locks for B02 must be generated by 64-bit CPython on Windows x64"
            )
        if _windows_product_type() != 1:
            parser.error(
                "Windows product locks for B02 must be generated on a Windows 11 workstation, not Windows Server"
            )
        if windows_build is None or windows_build < 22000:
            parser.error(
                "Windows product locks for B02 require Windows 11 build 22000 or newer"
            )
    with (ROOT / "pyproject.toml").open("rb") as handle:
        metadata = tomllib.load(handle)
    include_build_requirements = platform.system() == "Windows"
    build_requirements = list(metadata["build-system"]["requires"])
    declared = set(metadata["project"]["optional-dependencies"])
    if declared != set(PROFILES):
        parser.error(f"declared profile drift: expected {PROFILES}, found {sorted(declared)}")

    results: dict[str, object] = {}
    with tempfile.TemporaryDirectory(prefix="omni-profile-resolution-") as temporary:
        temp = Path(temporary)
        for profile in args.profiles:
            report_path = temp / f"{profile}.json"
            command = [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--dry-run",
                "--ignore-installed",
                "--report",
                str(report_path),
                f".[{profile}]",
            ]
            # The primary Windows source-checkout installer builds OMNI without
            # PEP 517 isolation after installing this lock. Include the exact
            # build backend there so a qualified install cannot perform a
            # hidden, unpinned network resolution while building local source.
            if include_build_requirements:
                command.extend(build_requirements)
            completed = subprocess.run(
                command,
                cwd=ROOT,
                text=True,
                capture_output=True,
                timeout=1200,
                check=False,
            )
            if completed.returncode:
                print(completed.stdout[-5000:], file=sys.stderr)
                print(completed.stderr[-5000:], file=sys.stderr)
                raise SystemExit(f"profile {profile} failed to resolve")
            report = json.loads(report_path.read_text())
            packages: list[dict[str, object]] = []
            for item in report["install"]:
                package = {
                    "name": item["metadata"]["name"],
                    "version": item["metadata"]["version"],
                    "requested": bool(item.get("requested", False)),
                    "url": item["download_info"]["url"],
                    "sha256": _sha256(item["download_info"]),
                }
                if package["name"].lower() != "omni-agi" and not package["sha256"]:
                    raise SystemExit(f"profile {profile} has unhashed dependency: {package}")
                packages.append(package)
            packages.sort(key=lambda value: (str(value["name"]).lower(), str(value["version"])))
            results[profile] = {
                "status": "pass",
                "resolved_count": len(packages),
                "packages": packages,
            }
            print(f"PASS {profile}: {len(packages)} distributions")

    lock_dir = args.lock_dir if args.lock_dir.is_absolute() else ROOT / args.lock_dir
    lock_dir.mkdir(parents=True, exist_ok=True)
    for profile in args.profiles:
        packages = results[profile]["packages"]  # type: ignore[index]
        (lock_dir / f"{profile}.txt").write_text(_lock_text(profile, packages), encoding="utf-8")

    output = args.output if args.output.is_absolute() else ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema_version": 1,
        "status": "pass",
        "generated_by": "scripts/resolve_profiles.py",
        "python": {
            "implementation": platform.python_implementation(),
            "version": platform.python_version(),
            "executable": str(Path(sys.executable).resolve()),
        },
        "platform": {
            "system": platform.system(),
            "release": platform.release(),
            "machine": platform.machine(),
            "pointer_bits": _pointer_bits(),
            "windows_build": _windows_build(),
            "windows_product_type": _windows_product_type(),
        },
        "supported_python": metadata["project"]["requires-python"],
        "build_system_requirements": build_requirements,
        "build_system_requirements_included": include_build_requirements,
        "profiles": results,
        "lock_directory": str(lock_dir.relative_to(ROOT)),
        "limitation": (
            f"Locks and resolver evidence are CPython 3.11 {platform.system()} "
            f"{platform.machine()} specific; they do not qualify any other platform. "
            "Resolution alone does not prove installation or runtime behavior."
        ),
    }
    output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {output.relative_to(ROOT)} and {len(args.profiles)} hashed lock files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
