#!/usr/bin/env python3
"""Resolve every declared B01 profile and emit exact, hashed CPython 3.11 locks."""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILES = ("core", "voice", "vision", "desktop", "dev", "all")


def _sha256(download_info: dict) -> str | None:
    archive = download_info.get("archive_info") or {}
    hashes = archive.get("hashes") or {}
    if hashes.get("sha256"):
        return str(hashes["sha256"])
    value = archive.get("hash")
    if isinstance(value, str) and value.startswith("sha256="):
        return value.split("=", 1)[1]
    return None


def _lock_text(profile: str, packages: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by scripts/resolve_profiles.py; do not edit.",
        f"# Profile: {profile}",
        f"# Interpreter: CPython {platform.python_version()}",
        f"# Platform: {platform.system()} {platform.machine()}",
        "# Install the OMNI wheel separately, then install this platform-specific lock with:",
        f"#   python -m pip install --no-deps --require-hashes -r {profile}.txt",
        "",
    ]
    for package in packages:
        if package["name"].lower() == "omni-agi":
            continue
        digest = package.get("sha256")
        if not digest:
            raise RuntimeError(f"resolved package has no SHA-256: {package}")
        lines.append(f"{package['name']}=={package['version']} --hash=sha256:{digest}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "quality/evidence/B01/profile-resolution.json",
    )
    parser.add_argument(
        "--lock-dir",
        type=Path,
        default=ROOT / "requirements/locks/cpython-3.11-linux-x86_64",
    )
    args = parser.parse_args()

    if sys.version_info[:2] != (3, 11) or platform.python_implementation() != "CPython":
        parser.error("B01 locks must be generated with CPython 3.11")
    with (ROOT / "pyproject.toml").open("rb") as handle:
        metadata = tomllib.load(handle)
    declared = set(metadata["project"]["optional-dependencies"])
    if declared != set(PROFILES):
        parser.error(f"declared profile drift: expected {PROFILES}, found {sorted(declared)}")

    results: dict[str, object] = {}
    with tempfile.TemporaryDirectory(prefix="omni-profile-resolution-") as temporary:
        temp = Path(temporary)
        for profile in PROFILES:
            report_path = temp / f"{profile}.json"
            command = [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--dry-run",
                "--ignore-installed",
                "--report",
                str(report_path),
                f".[{profile}]",
            ]
            completed = subprocess.run(
                command,
                cwd=ROOT,
                text=True,
                capture_output=True,
                timeout=1200,
                check=False,
            )
            if completed.returncode:
                print(completed.stdout[-5000:], file=sys.stderr)
                print(completed.stderr[-5000:], file=sys.stderr)
                raise SystemExit(f"profile {profile} failed to resolve")
            report = json.loads(report_path.read_text())
            packages: list[dict[str, object]] = []
            for item in report["install"]:
                package = {
                    "name": item["metadata"]["name"],
                    "version": item["metadata"]["version"],
                    "requested": bool(item.get("requested", False)),
                    "url": item["download_info"]["url"],
                    "sha256": _sha256(item["download_info"]),
                }
                if package["name"].lower() != "omni-agi" and not package["sha256"]:
                    raise SystemExit(f"profile {profile} has unhashed dependency: {package}")
                packages.append(package)
            packages.sort(key=lambda value: (str(value["name"]).lower(), str(value["version"])))
            results[profile] = {
                "status": "pass",
                "resolved_count": len(packages),
                "packages": packages,
            }
            print(f"PASS {profile}: {len(packages)} distributions")

    lock_dir = args.lock_dir if args.lock_dir.is_absolute() else ROOT / args.lock_dir
    lock_dir.mkdir(parents=True, exist_ok=True)
    for profile in PROFILES:
        packages = results[profile]["packages"]  # type: ignore[index]
        (lock_dir / f"{profile}.txt").write_text(_lock_text(profile, packages), encoding="utf-8")

    output = args.output if args.output.is_absolute() else ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema_version": 1,
        "status": "pass",
        "generated_by": "scripts/resolve_profiles.py",
        "python": {
            "implementation": platform.python_implementation(),
            "version": platform.python_version(),
            "executable": str(Path(sys.executable).resolve()),
        },
        "platform": {
            "system": platform.system(),
            "release": platform.release(),
            "machine": platform.machine(),
        },
        "supported_python": metadata["project"]["requires-python"],
        "profiles": results,
        "lock_directory": str(lock_dir.relative_to(ROOT)),
        "limitation": "Locks and resolver evidence are CPython 3.11 Linux x86_64 specific; no Windows/macOS qualification is claimed.",
    }
    output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {output.relative_to(ROOT)} and {len(PROFILES)} hashed lock files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
