# Fresh Windows 11 x64 B02 install/lifecycle/uninstall qualification.
# Run in a disposable checkout from Windows PowerShell 5.1 or newer.

[CmdletBinding()]
param(
    [switch]$KeepInstalled
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version 3.0
$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $root

function Assert-True {
    param([bool]$Condition, [string]$Message)
    if (-not $Condition) { throw $Message }
}

function Invoke-Step {
    param([string]$Name, [scriptblock]$Action)
    Write-Host "`n=== $Name ==="
    & $Action
    if ($LASTEXITCODE -ne 0) { throw "$Name failed with exit code $LASTEXITCODE" }
}

Assert-True ($env:OS -eq "Windows_NT") "This qualification must run on Windows."
$gitStatus = @(& git status --porcelain=v1 --untracked-files=all)
Assert-True ($LASTEXITCODE -eq 0) "Could not inspect checkout cleanliness."
Assert-True ($gitStatus.Count -eq 0) "Qualification requires an exact clean checkout; commit the native lock and resolver evidence first."

$evidenceDir = Join-Path $root "quality\evidence\B02"
New-Item -ItemType Directory -Force -Path $evidenceDir | Out-Null
$transcriptPath = Join-Path $evidenceDir "windows-install-qualification.log"
Start-Transcript -Path $transcriptPath -Force | Out-Null

. (Join-Path $PSScriptRoot "windows_platform.ps1")
$windowsPlatform = Assert-OmniWindows11X64

$lockPath = "$root\requirements\locks\cpython-3.11-windows-x86_64\core.txt"
$resolutionPath = "$root\quality\evidence\B02\cpython-3.11-windows-x86_64-profile-resolution.json"
Assert-True (Test-Path $lockPath) "Native Windows core lock is missing. Generate it on this host before qualification."
Assert-True (Test-Path $resolutionPath) "Native Windows resolver evidence is missing."
$resolution = (Get-Content -Raw -Path $resolutionPath) | ConvertFrom-Json
Assert-True ($resolution.status -eq "pass") "Native Windows resolver evidence does not report pass."
Assert-True ($resolution.python.implementation -eq "CPython" -and $resolution.python.version.StartsWith("3.11.")) "Resolver evidence was not generated by CPython 3.11."
$resolutionMachine = $resolution.platform.machine.ToLowerInvariant()
Assert-True ($resolution.platform.system -eq "Windows" -and $resolutionMachine -in @("amd64", "x86_64")) "Resolver evidence was not generated on native Windows x64."
Assert-True ([int]$resolution.platform.pointer_bits -eq 64) "Resolver evidence was not generated by a 64-bit CPython interpreter."
Assert-True ([int]$resolution.platform.windows_build -ge 22000) "Resolver evidence predates the minimum Windows 11 build 22000 boundary."
Assert-True ([int]$resolution.platform.windows_product_type -eq 1) "Resolver evidence was not generated on a Windows workstation product."
Assert-True ($resolution.build_system_requirements_included -eq $true) "Resolver evidence omitted the exact local-source build requirements."
Assert-True ($resolution.profiles.core.status -eq "pass") "Resolver evidence does not contain a passing core profile."
$corePackageNames = @($resolution.profiles.core.packages | ForEach-Object { $_.name.ToLowerInvariant() })
Assert-True ($corePackageNames -contains "setuptools" -and $corePackageNames -contains "wheel") "Native Windows core lock omits setuptools or wheel."
Assert-True (-not (Test-Path "$root\.venv")) "Qualification requires a clean checkout without .venv."
Assert-True (-not (Test-Path "$root\frontend_next\node_modules")) "Qualification requires a clean checkout without node_modules."
Assert-True (-not (Test-Path "$root\frontend_next\.next")) "Qualification requires a clean checkout without a frontend build."

$originalDataDir = $env:OMNI_DATA_DIR
$qualificationData = Join-Path ([IO.Path]::GetTempPath()) "omni-b02-qualification-$PID"
Assert-True (-not (Test-Path $qualificationData)) "Qualification data directory already exists: $qualificationData"
$env:OMNI_DATA_DIR = $qualificationData

Invoke-Step "First clean install" { & "$root\scripts\install.ps1" -Core }
$python = "$root\.venv\Scripts\python.exe"
Assert-True (Test-Path $python) "First install did not create the managed environment."
Assert-True (Test-Path "$root\frontend_next\.next\BUILD_ID") "First install did not create a frontend build."

$config = (& $python -m omni_v2.core.runtime_cli --json config show | Out-String) | ConvertFrom-Json
$configPath = [string]$config.config_path
Assert-True (Test-Path $configPath) "Canonical config was not initialized."
$configBefore = (Get-FileHash -Algorithm SHA256 $configPath).Hash
$pythonMetadata = ((& $python -c "import json, platform, sys; print(json.dumps({'implementation': platform.python_implementation(), 'version': platform.python_version(), 'architecture': platform.machine(), 'executable': sys.executable}))" | Out-String) | ConvertFrom-Json)
Assert-True ($pythonMetadata.implementation -eq "CPython" -and $pythonMetadata.version.StartsWith("3.11.") -and $pythonMetadata.architecture.ToLowerInvariant() -in @("amd64", "x86_64")) "Managed interpreter is not CPython 3.11 x64."
$nodeVersion = (& node --version).Trim()
$corepackCommand = Get-Command corepack -ErrorAction Stop
$corepackVersion = (& $corepackCommand.Source --version).Trim()
$npmVersion = (& $corepackCommand.Source "npm@12.0.2" --version).Trim()
Assert-True ($LASTEXITCODE -eq 0 -and $npmVersion -eq "12.0.2") "Corepack did not resolve exact npm 12.0.2 during qualification."
$commitSha = (& git rev-parse HEAD).Trim()

Invoke-Step "Managed start before second install" { & "$root\scripts\start.ps1" -NoBrowser }
$beforeReinstall = (& $python -m omni_v2.core.runtime_cli --json status | Out-String) | ConvertFrom-Json
Assert-True $beforeReinstall.ok "Status did not verify the generation before reinstall."
Assert-True (@($beforeReinstall.services).Count -eq 2) "Full startup did not own backend and frontend."
$preinstallPids = @($beforeReinstall.services | ForEach-Object { [int]$_.pid })

Invoke-Step "Idempotent second install while running" { & "$root\scripts\install.ps1" -Core }
Assert-True ((Get-FileHash -Algorithm SHA256 $configPath).Hash -eq $configBefore) "Second install overwrote canonical configuration."
foreach ($pidValue in $preinstallPids) {
    Assert-True (-not (Get-Process -Id $pidValue -ErrorAction SilentlyContinue)) "Second install left old PID $pidValue running."
}
Assert-True (-not (Test-Path ([string]$config.runtime_state_path))) "Second install left stale runtime state."

Invoke-Step "Managed start after second install" { & "$root\scripts\start.ps1" -NoBrowser }
$first = (& $python -m omni_v2.core.runtime_cli --json status | Out-String) | ConvertFrom-Json
Assert-True $first.ok "Status did not verify the post-install generation."
Assert-True (@($first.services).Count -eq 2) "Full startup did not own backend and frontend."
$firstPids = @($first.services | ForEach-Object { [int]$_.pid })

Invoke-Step "Idempotent second managed start" { & "$root\scripts\start.ps1" -NoBrowser }
$idempotent = (& $python -m omni_v2.core.runtime_cli --json status | Out-String) | ConvertFrom-Json
Assert-True $idempotent.ok "Second managed start did not preserve a ready generation."
$idempotentPids = @($idempotent.services | ForEach-Object { [int]$_.pid })
Assert-True (-not (@($firstPids | Where-Object { $idempotentPids -notcontains $_ }))) "Second managed start replaced an already healthy PID."
Assert-True (-not (@($idempotentPids | Where-Object { $firstPids -notcontains $_ }))) "Second managed start changed the healthy process set."

Invoke-Step "Managed restart" { & "$root\scripts\start.ps1" -Restart -NoBrowser }
$second = (& $python -m omni_v2.core.runtime_cli --json status | Out-String) | ConvertFrom-Json
Assert-True $second.ok "Status did not verify the restarted generation."
$secondPids = @($second.services | ForEach-Object { [int]$_.pid })
Assert-True (-not (@($firstPids | Where-Object { $secondPids -contains $_ }))) "Restart reused an old PID."
foreach ($pidValue in $firstPids) {
    Assert-True (-not (Get-Process -Id $pidValue -ErrorAction SilentlyContinue)) "Old PID $pidValue survived restart."
}

Invoke-Step "Managed stop" { & $python -m omni_v2.core.runtime_cli stop }
foreach ($pidValue in $secondPids) {
    Assert-True (-not (Get-Process -Id $pidValue -ErrorAction SilentlyContinue)) "PID $pidValue survived stop."
}
Assert-True (-not (Test-Path ([string]$config.runtime_state_path))) "Runtime state survived stop."

Invoke-Step "Safe uninstall with data preservation" { & "$root\scripts\uninstall.ps1" -Confirm:$false }
Assert-True (-not (Test-Path "$root\.venv")) "Uninstall left .venv behind."
Assert-True (-not (Test-Path "$root\frontend_next\node_modules")) "Uninstall left node_modules behind."
Assert-True (-not (Test-Path "$root\frontend_next\.next")) "Uninstall left the frontend build behind."
Assert-True (Test-Path $configPath) "Default uninstall deleted canonical user data."
Assert-True ((Get-FileHash -Algorithm SHA256 $configPath).Hash -eq $configBefore) "Uninstall changed preserved configuration."

Invoke-Step "Explicit user-data uninstall" { & "$root\scripts\uninstall.ps1" -RemoveUserData -Confirm:$false }
Assert-True (-not (Test-Path $qualificationData)) "Explicit user-data uninstall left canonical data behind."
Assert-True (Test-Path "$root\pyproject.toml") "Uninstall damaged the source checkout."
Invoke-Step "Idempotent second uninstall" { & "$root\scripts\uninstall.ps1" -RemoveUserData -Confirm:$false }
Assert-True (-not (Test-Path $qualificationData)) "Second uninstall recreated or retained canonical data."

if ($null -eq $originalDataDir) {
    Remove-Item Env:OMNI_DATA_DIR -ErrorAction SilentlyContinue
} else {
    $env:OMNI_DATA_DIR = $originalDataDir
}

if ($KeepInstalled) {
    Invoke-Step "Restore installation with the operator's normal data path" { & "$root\scripts\install.ps1" -Core }
}

$evidence = [ordered]@{
    schema_version = 1
    batch = "B02"
    status = "pass"
    commit_sha = $commitSha
    completed_at_utc = [DateTime]::UtcNow.ToString("o")
    platform = [ordered]@{
        os = "Windows"
        caption = $windowsPlatform.Caption
        version = $windowsPlatform.Version
        build = $windowsPlatform.Build
        product_type = $windowsPlatform.ProductType
        architecture = $windowsPlatform.Architecture
    }
    tools = [ordered]@{
        python = $pythonMetadata
        node = $nodeVersion
        corepack = $corepackVersion
        npm = $npmVersion
        powershell = $PSVersionTable.PSVersion.ToString()
    }
    artifacts = [ordered]@{
        core_lock = "requirements/locks/cpython-3.11-windows-x86_64/core.txt"
        core_lock_sha256 = (Get-FileHash -Algorithm SHA256 $lockPath).Hash.ToLowerInvariant()
        resolver_evidence = "quality/evidence/B02/cpython-3.11-windows-x86_64-profile-resolution.json"
        transcript = "quality/evidence/B02/windows-install-qualification.log"
    }
    assertions = @(
        "fresh checkout installation",
        "native hashed core lock installation",
        "canonical configuration initialization",
        "managed backend and frontend readiness",
        "second install while running stops owned PIDs and preserves configuration",
        "second start preserves an already healthy generation",
        "restart replaces owned PIDs",
        "stop removes owned process tree and state",
        "default uninstall removes generated assets and preserves user data",
        "explicit user-data uninstall removes only validated canonical data",
        "second uninstall is idempotent and leaves the source checkout intact"
    )
    qualification_data_removed = $true
    restored_installation = [bool]$KeepInstalled
}
$evidencePath = Join-Path $evidenceDir "windows-install-qualification.json"
$evidence | ConvertTo-Json -Depth 6 | Set-Content -Path $evidencePath -Encoding UTF8

Write-Host "`nB02 Windows install/start/stop/restart/second-install/uninstall qualification: PASS"
Write-Host "Evidence: $evidencePath"
Stop-Transcript | Out-Null
