"""Plugin Manager - Extensible Command System with alias routing"""
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from loguru import logger

@dataclass
class CommandMetadata:
    name: str
    category: str
    description: str
    patterns: List[str]
    examples: List[str] = None

@dataclass
class CommandResult:
    success: bool
    message: str
    data: Any = None
    error: Optional[str] = None
    
    @classmethod
    def ok(cls, message: str, data: Any = None):
        return cls(success=True, message=message, data=data)
    
    @classmethod
    def error(cls, message: str, error: str = None):
        return cls(success=False, message=message, error=error or message)

class CommandPlugin:
    """Base class for command plugins"""
    metadata: CommandMetadata = None
    # Optional: list of additional action names this plugin handles
    SUPPORTED_ACTIONS: List[str] = []
    
    async def execute(self, entities: Dict[str, Any], context: Dict[str, Any]) -> CommandResult:
        raise NotImplementedError

class PluginManager:
    """Manages command plugins with dynamic loading and alias routing."""
    # Category -> canonical plugin name mapping (fallback)
    CATEGORY_FALLBACKS = {
        "browser": "browser_navigate",
        "windows": "windows_launch",
        "system": "system_screenshot",
        "omni": "omni_help",
        "alpha": "alpha_control",
        "accessibility": "accessibility_mode",
        "vscode": "vscode_control",
        "integrations": None,  # needs sub-routing
        "performance": "performance_check",
    }

    # Explicit alias map for every action generated by CommandRegistry
    ACTION_ALIASES: Dict[str, str] = {
        # browser
        "browser_navigate": "browser_navigate",
        "browser_search": "browser_navigate",
        "browser_click": "browser_navigate",
        "browser_type": "browser_navigate",
        "browser_scroll": "browser_navigate",
        # windows
        "windows_launch": "windows_launch",
        "windows_close": "windows_launch",
        "windows_minimize": "windows_launch",
        "windows_maximize": "windows_launch",
        # system + performance
        "system_screenshot": "system_screenshot",
        "system_copy": "system_screenshot",
        "system_paste": "system_screenshot",
        "system_volume": "system_screenshot",
        "performance": "performance_check",
        "performance_optimize": "performance_check",
        "integrations_performance": "performance_check",
        "integrations_optimize": "performance_check",
        # omni
        "omni_help": "omni_help",
        "omni_settings": "omni_help",
        "omni_status": "omni_help",
        "omni_repeat": "omni_help",
        "omni_undo": "omni_help",
        # alpha
        "alpha_record": "alpha_control",
        "alpha_save_macro": "alpha_control",
        "alpha_cancel_recording": "alpha_control",
        "alpha_run_macro": "alpha_control",
        "alpha_show_hints": "alpha_control",
        "alpha_screen_desc": "alpha_control",
        "alpha_find": "alpha_control",
        "alpha_learn": "alpha_control",
        # accessibility
        "accessibility_high_contrast": "accessibility_mode",
        "accessibility_large_text": "accessibility_mode",
        "accessibility_audio_only": "accessibility_mode",
        "screen_description": "screen_description",
        "alpha_screen_description": "screen_description",
        # vscode
        "vscode_open": "vscode_control",
        "vscode_terminal": "vscode_control",
        "vscode_save": "vscode_control",
        "vscode_create": "vscode_control",
        # integrations -> sub-routing
        "integrations_send_email": "gmail_control",
        "integrations_read_emails": "gmail_control",
        "integrations_count_emails": "gmail_control",
        "integrations_schedule_meeting": "calendar_control",
        "integrations_show_calendar": "calendar_control",
        "integrations_cancel_event": "calendar_control",
        "integrations_lights_on": "smarthome_control",
        "integrations_lights_off": "smarthome_control",
        "integrations_set_temperature": "smarthome_control",
        "integrations_lock_door": "smarthome_control",
        "integrations_unlock_door": "smarthome_control",
        "integrations_show_camera": "smarthome_control",
        "integrations_performance": "performance_check",
    }

    def __init__(self):
        self._plugins: Dict[str, CommandPlugin] = {}
        self._categories: Dict[str, List[str]] = {}
        self._action_to_plugin: Dict[str, str] = {}  # action -> canonical plugin name
        logger.info("PluginManager initialized with alias routing")
    
    def register(self, plugin: CommandPlugin) -> None:
        if not plugin.metadata:
            return
        name = plugin.metadata.name
        self._plugins[name] = plugin
        category = plugin.metadata.category
        if category not in self._categories:
            self._categories[category] = []
        self._categories[category].append(name)

        # Register explicit supported actions
        for alias in getattr(plugin, 'SUPPORTED_ACTIONS', []):
            self._action_to_plugin[alias] = name

        logger.info(f"Registered: {name} (category={category})")
    
    def get_plugin(self, name: str) -> Optional[CommandPlugin]:
        """Resolve plugin by exact name, alias map, or category fallback."""
        if not name:
            return None

        # 1. Direct hit
        if name in self._plugins:
            return self._plugins[name]

        # 2. Explicit action -> plugin cache built at register time
        if name in self._action_to_plugin:
            canonical = self._action_to_plugin[name]
            if canonical in self._plugins:
                return self._plugins[canonical]

        # 3. Global alias table
        if name in self.ACTION_ALIASES:
            canonical = self.ACTION_ALIASES[name]
            if canonical in self._plugins:
                return self._plugins[canonical]

        # 4. Category prefix fallback
        # e.g. browser_search -> browser category -> browser_navigate
        if "_" in name:
            prefix = name.split("_")[0]
            # special case: integrations_ subrouting by keyword
            if prefix == "integrations":
                # try to infer from name
                lower = name.lower()
                if "email" in lower:
                    return self._plugins.get("gmail_control") or self._plugins.get("browser_navigate")
                if "calendar" in lower or "meeting" in lower or "event" in lower:
                    return self._plugins.get("calendar_control") or self._plugins.get("browser_navigate")
                if "light" in lower or "temperature" in lower or "door" in lower or "camera" in lower or "lock" in lower:
                    return self._plugins.get("smarthome_control") or self._plugins.get("system_screenshot")
                if "performance" in lower or "status" in lower or "memory" in lower:
                    return self._plugins.get("performance_check")
                # generic integrations fallback
                return self._plugins.get("gmail_control") or self._plugins.get("system_screenshot")

            fallback_canonical = self.CATEGORY_FALLBACKS.get(prefix)
            if fallback_canonical and fallback_canonical in self._plugins:
                return self._plugins[fallback_canonical]

            # also try searching any plugin whose category matches prefix
            for cname, plugin in self._plugins.items():
                if plugin.metadata.category == prefix:
                    return plugin
                if plugin.metadata.category in name:
                    return plugin

        # 5. Last resort: fuzzy contains
        name_lower = name.lower()
        for cname, plugin in self._plugins.items():
            if cname.lower() in name_lower or name_lower in cname.lower():
                return plugin

        # 6. Still not found
        logger.warning(f"Plugin not found for action '{name}'. Available: {list(self._plugins.keys())}")
        return None
    
    def get_all_plugins(self) -> List[CommandPlugin]:
        return list(self._plugins.values())
    
    async def execute(self, action: str, entities: Dict[str, Any], context: Dict[str, Any] = None) -> CommandResult:
        plugin = self.get_plugin(action)
        if not plugin:
            return CommandResult.error(f"Unknown command: {action}")
        try:
            return await plugin.execute(entities, context or {})
        except Exception as e:
            logger.error(f"Plugin {action} error: {e}")
            return CommandResult.error(str(e), error=str(e))
    
    def get_help_text(self) -> str:
        lines = ["Available Commands:", ""]
        for category in self._categories:
            lines.append(f"--- {category.upper()} ---")
            for name in self._categories[category]:
                p = self._plugins.get(name)
                if p and p.metadata:
                    lines.append(f"  {p.metadata.name}: {p.metadata.description}")
        return "\n".join(lines)
